//
// Created by castle on 4/16/19.
//
#ifndef FFMPEGANDROIDPLAYER_PLAYERSTATE_H
#define FFMPEGANDROIDPLAYER_PLAYERSTATE_H;
//用于控制自己独有的状态
#define OPENSLES_PLAYERSTATE_PREPARED ((SLuint32) 0x00000001)
#define OPENSLES_PLAYERSTATE_UNINITED ((SLuint32) 0x00000002)
#endif //FFMPEGANDROIDPLAYER_PLAYERSTATE_H
